name: Daily Insider Report

on:
  schedule:
    - cron: '0 23 * * 1-5'  # Runs at 7PM ET (23:00 UTC) weekdays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run report generator
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          MARKET_DATA_API_KEY: ${{ secrets.MARKET_DATA_API_KEY }}
        run: python jobs/main.py

      - name: Commit signal history
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/signals_history.csv
          git diff --staged --quiet || git commit -m "Daily signal update: $(date +'%Y-%m-%d')"
          
      - name: Push changes
        run: |
          git push || echo "No changes to push"
