name: Daily Insider Report

on:
  schedule:
    - cron: '0 11 * * 1-5'  # Runs at 7AM ET (11:00 UTC) weekdays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run report generator
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          MARKET_DATA_API_KEY: ${{ secrets.MARKET_DATA_API_KEY }}
        run: python jobs/main.py

      - name: Check if history file exists
        id: check_history
        run: |
          if [ -f "data/signals_history.csv" ]; then
            echo "history_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Signal history file created"
          else
            echo "history_exists=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No signal history generated (likely no buy signals detected)"
          fi

      - name: Commit signal history
        if: steps.check_history.outputs.history_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/signals_history.csv
          git diff --staged --quiet || git commit -m "Daily signal update: $(date +'%Y-%m-%d')"
          
      - name: Push changes
        if: steps.check_history.outputs.history_exists == 'true'
        run: |
          git push
